# Generated by Django 6.0 on 2026-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siriapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=7)),
                ("category", models.CharField(blank=True, default="", max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("period", "category")},
            },
        ),
    ]
